name: AI_Car_Assistanta
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: AI_assistant_cars_catalog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d AI_assistant_cars_catalog" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s


volumes:
  postgres_data:
